// <auto-generated />
using System;
using DocPipeline.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DocPipeline.Infrastructure.Data.Migrations;

[DbContext(typeof(AppDbContext))]
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.6")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("DocPipeline.Domain.Entities.Document", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
            b.Property<string>("ContentType").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
            b.Property<string>("ErrorMessage").HasMaxLength(2000).HasColumnType("nvarchar(2000)");
            b.Property<string>("ExtractedDataJson").HasColumnType("nvarchar(max)");
            b.Property<string>("FileName").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
            b.Property<long>("FileSizeBytes").HasColumnType("bigint");
            b.Property<DateTime?>("ProcessedAt").HasColumnType("datetime2");
            b.Property<byte[]>("RowVersion").IsConcurrencyToken().IsRequired().ValueGeneratedOnAddOrUpdate().HasColumnType("rowversion");
            b.Property<int>("Status").IsRequired().HasColumnType("int");
            b.Property<string>("StoragePath").IsRequired().HasMaxLength(1000).HasColumnType("nvarchar(1000)");
            b.Property<DateTime>("UploadedAt").HasColumnType("datetime2");
            b.Property<string>("UploadedByUserId").IsRequired().HasMaxLength(450).HasColumnType("nvarchar(450)");
            b.HasKey("Id");
            b.HasIndex("Status").HasDatabaseName("IX_Documents_Status");
            b.HasIndex("UploadedAt").HasDatabaseName("IX_Documents_UploadedAt");
            b.HasIndex("UploadedByUserId").HasDatabaseName("IX_Documents_UploadedByUserId");
            b.ToTable("Documents");
        });
#pragma warning restore 612, 618
    }
}
